chapter_1_time = "0:25"
chapter_2_time = "3:13"
chapter_3_time = "5:53"
chapter_4_time = "7:56"
chapter_5_time = "10:37"

study_link1 = "https://www.youtube.com/watch?v=920R8jClXNk"
study_link2 = "https://www.youtube.com/watch?v=8AJ9cYbhgvQ"
study_link3 = "https://www.youtube.com/watch?v=hBj195oor1U"
study_link4 = "https://www.youtube.com/watch?v=0obzwmMrzt0"
study_link5 = "https://www.youtube.com/watch?v=KC8wjBN-Ya4"
study_link6 = "https://www.youtube.com/watch?v=sfik4rhm2ps"
study_link7 = "https://www.youtube.com/watch?v=FmaYSxu1oVE"
study_link8 = "https://www.youtube.com/watch?v=m45qpVFWYgI"
study_link9 = "https://www.youtube.com/watch?v=MhGoqJRsWVw"

sermon_link1 = "https://www.youtube.com/watch?v=GBrV75GLSHw"
sermon_link2 = "https://www.youtube.com/watch?v=bGsSo6UtOE0"
sermon_link3 = "https://www.youtube.com/watch?v=xqgeT26BAnE"
sermon_link4 = "https://www.youtube.com/watch?v=0lvGW5tw-wA"