chapter_1_time = "0:25"
chapter_2_time = "2:49"
chapter_3_time = "5:44"
chapter_4_time = "7:30"
chapter_5_time = "10:15"

study_link1 = "https://www.youtube.com/watch?v=rkBmCnW6Quo"
study_link2 = "https://www.youtube.com/watch?v=aRMWZIdSBIQ"
study_link3 = "https://www.youtube.com/watch?v=sS6RVMWsdII"
study_link4 = "https://www.youtube.com/watch?v=VMfGPKBm5BY"
study_link5 = "https://www.youtube.com/watch?v=0Jac9z4qa2Q"
study_link6 = "https://www.youtube.com/watch?v=2SRkMW9dyrI"
study_link7 = "https://www.youtube.com/watch?v=PKXBdhJwTBQ"
study_link8 = "https://www.youtube.com/watch?v=11FtG8Nbn8Y"
study_link9 = "https://www.youtube.com/watch?v=BqcwcxoxoUo"

sermon_link1 = "https://www.youtube.com/watch?v=OEeiFIRrNXg"
sermon_link2 = "https://www.youtube.com/watch?v=FuJiVLIYhfI"
sermon_link3 = "https://www.youtube.com/watch?v=QV7LxPy6KKg"
sermon_link4 = "https://www.youtube.com/watch?v=7fdi1D99Ung"