chapter_1_time = "0:25"
chapter_2_time = "3:33"
chapter_3_time = "4:46"
chapter_4_time = "6:41"
chapter_5_time = "8:40"
chapter_6_time = "10:30"

study_link1 = "https://www.youtube.com/watch?v=PJ6z9uhOXEA"
study_link2 = "https://www.youtube.com/watch?v=tirvyfSDP6E"
study_link3 = "https://www.youtube.com/watch?v=a11ASw5NRUw"
study_link4 = "https://www.youtube.com/watch?v=2uBZlKccWZk"
study_link5 = "https://www.youtube.com/watch?v=6GKNNu8Qg_I"
study_link6 = "https://www.youtube.com/watch?v=64mz12_PNY0"
study_link7 = "https://www.youtube.com/watch?v=xc_U_jzpZro"
study_link8 = "https://www.youtube.com/watch?v=4csMHZuPlWY"

sermon_link1 = "https://www.youtube.com/watch?v=BQDRdC0h1mM"
sermon_link2 = "https://www.youtube.com/watch?v=QxKRH-9IRCg"
sermon_link3 = "https://www.youtube.com/watch?v=Dt9RKNWuv5o"