chapter_1_time = "0:25"
chapter_2_time = "3:26"
chapter_3_time = "5:10"
chapter_4_time = "6:39"
chapter_5_time = "8:24"
chapter_6_time = "10:25"

study_link1 = "https://www.youtube.com/watch?v=2_-kxwCDrOg"
study_link2 = "https://www.youtube.com/watch?v=UMGTzNJc8Ys"
study_link3 = "https://www.youtube.com/watch?v=tM4mjTK2IfM"
study_link4 = "https://www.youtube.com/watch?v=fnsCL7WNua4"
study_link5 = "https://www.youtube.com/watch?v=8IseOKwjiNw"
study_link6 = "https://www.youtube.com/watch?v=cSJV5Vs3NZ4"

sermon_link1 = "https://www.youtube.com/watch?v=07x8335999I"
sermon_link2 = "https://www.youtube.com/watch?v=E44Ghw9bO4g"
sermon_link3 = "https://www.youtube.com/watch?v=WX377Qn44Ao"
sermon_link4 = "https://www.youtube.com/watch?v=RudgOdcgsxI"
sermon_link5 = "https://www.youtube.com/watch?v=rkrlPP8s3_o"