chapter_1_time = "0:25"
chapter_2_time = "2:36"
chapter_3_time = "4:23"
chapter_4_time = "5:47"
chapter_5_time = "7:37"

study_link1 = "https://www.youtube.com/watch?v=x3V42MW3EjE"
study_link2 = "https://www.youtube.com/watch?v=pn69quaqWO8"
study_link3 = "https://www.youtube.com/watch?v=x1GgGyV8ZQc"
study_link4 = "https://www.youtube.com/watch?v=NWaLb_-MOxI"
study_link5 = "https://www.youtube.com/watch?v=2WDOOt4qZL0"
study_link6 = "https://www.youtube.com/watch?v=3gr4kn2tf_k"

sermon_link1 = "https://www.youtube.com/watch?v=q2matQzJQPw"
sermon_link2 = "https://www.youtube.com/watch?v=pwv6qot7MZ4"
sermon_link3 = "https://www.youtube.com/watch?v=Y8JqWX4DZx8"