chapter_1_time = "0:25"
chapter_2_time = "2:28"
chapter_3_time = "3:55"
chapter_4_time = "8:03"
chapter_5_time = "11:29"

study_link1 = "https://www.youtube.com/@ExpeditionBible"
study_link2 = "https://www.youtube.com/watch?v=Vq2KAlCR14Q"
study_link3 = "https://www.youtube.com/watch?v=tnu7mCsZ8Kw"
study_link4 = "https://www.youtube.com/watch?v=24r4OwDIW2Y"
study_link5 = "https://www.youtube.com/watch?v=M2VJelWl_Fs"
study_link6 = "https://www.youtube.com/watch?v=Mc4B7dS9a88"
study_link7 = "https://www.youtube.com/watch?v=RCPozrJSBwg"
study_link8 = "https://www.youtube.com/watch?v=J2sd7RrpccQ"
study_link9 = "https://www.youtube.com/watch?v=OaDTHqPuwb8"

sermon_link1 = "https://www.youtube.com/watch?v=kDxYyXKUUv0"
sermon_link2 = "https://www.youtube.com/watch?v=Dy8ZEA4TGbk"
sermon_link3 = "https://www.youtube.com/watch?v=CXsPqrlOPrI"