chapter_1_time = "0:25"
chapter_2_time = "1:57"
chapter_3_time = "4:49"
chapter_4_time = "6:23"
chapter_5_time = "8:02"
chapter_6_time = "9:29"

study_link1 = "https://www.youtube.com/watch?v=JaFRMaqHAdY"
study_link2 = "https://www.youtube.com/watch?v=0G2S5ziDcO0"
study_link3 = "https://www.youtube.com/watch?v=oXEgbM2tSXs"
study_link4 = "https://www.youtube.com/watch?v=DieWtjcS5uo"
study_link5 = "https://www.youtube.com/watch?v=SL8mJQ39zjw"
study_link6 = "https://www.youtube.com/watch?v=7JpLwD-igQ4"
study_link7 = "https://www.youtube.com/watch?v=Hr3PkGXYRvI"

sermon_link1 = "https://www.youtube.com/watch?v=dT0w4w4qI3s"
sermon_link2 = "https://www.youtube.com/watch?v=oAslP8N1z4Y"
sermon_link3 = "https://www.youtube.com/watch?v=nDQC45_RA2c"
sermon_link4 = "https://www.youtube.com/watch?v=tMKqbGuG0NY"
sermon_link5 = "https://www.youtube.com/watch?v=3vmvZIAGKJo"