chapter_1_time = "0:25"
chapter_2_time = "2:33"
chapter_3_time = "4:31"
chapter_4_time = "7:22"
chapter_5_time = "8:37"
chapter_6_time = "11:21"

study_link1 = "https://www.youtube.com/watch?v=m45qpVFWYgI"
study_link2 = "https://www.youtube.com/watch?v=MhGoqJRsWVw"
study_link3 = "https://www.youtube.com/watch?v=1FbCcen5eek"
study_link4 = "https://www.youtube.com/watch?v=UWQiFKVaWVk"
study_link5 = "https://www.youtube.com/watch?v=ZhnbxeYwwIw"
study_link6 = "https://www.youtube.com/watch?v=79CNv3gcdJI"
study_link7 = "https://www.youtube.com/watch?v=mrO9sqMpdus"
study_link8 = "https://www.youtube.com/watch?v=EHATEltE3ww"
study_link9 = "https://www.youtube.com/watch?v=ZeLmZr88iOA"

sermon_link1 = "https://www.youtube.com/watch?v=-n1svH4_0s8"
sermon_link2 = "https://www.youtube.com/watch?v=owskaFH0sME"
sermon_link3 = "https://www.youtube.com/watch?v=yBIyWEWgCPY"
sermon_link4 = "https://www.youtube.com/watch?v=BBfcnp0dcKM"