chapter_1_time = "0:25"
chapter_2_time = "4:07"
chapter_3_time = "6:59"
chapter_4_time = "9:53"
chapter_5_time = "12:27"

study_link1 = "https://www.youtube.com/watch?v=R7Z6ro4-Ef4"
study_link2 = "https://www.youtube.com/watch?v=xlJE_gjk0TA"
study_link3 = "https://www.youtube.com/watch?v=w5b7OdWGmwA"
study_link4 = "https://www.youtube.com/watch?v=6OFw_1rMUtU"
study_link5 = "https://www.youtube.com/watch?v=oK5sum-LFFA"
study_link6 = "https://www.youtube.com/watch?v=mBo5TEqpiIg"
study_link7 = "https://www.youtube.com/watch?v=C0oE1oPWt-k"
study_link8 = "https://www.youtube.com/watch?v=QDPSEbS54aY"
study_link9 = "https://www.youtube.com/watch?v=xuXO82T7Kpo"

sermon_link1 = "https://www.youtube.com/watch?v=0mMPsRsPzfs"
sermon_link2 = "https://www.youtube.com/watch?v=53o665Z3ziE"
sermon_link3 = "https://www.youtube.com/watch?v=IdBvaUY9VEo"
sermon_link4 = "https://www.youtube.com/watch?v=P0RNve6DG6M"