chapter_1_time = "0:25"
chapter_2_time = "3:15"
chapter_3_time = "5:10"
chapter_4_time = "7:22"
chapter_5_time = "11:09"

study_link1 = "https://www.youtube.com/watch?v=n6wKQGiBmHA"
study_link2 = "https://www.youtube.com/watch?v=UnKgXCuy7tM"
study_link3 = "https://www.youtube.com/watch?v=rEPuC2jUctY"
study_link4 = "https://www.youtube.com/watch?v=xnNLajNNZPI"
study_link5 = "https://www.youtube.com/watch?v=ZXGSH3jRRtQ"
study_link6 = "https://www.youtube.com/watch?v=IVjJFReBW64"
study_link7 = ""

sermon_link1 = "https://www.youtube.com/watch?v=FojLxsDlV3g"
sermon_link2 = "https://www.youtube.com/watch?v=FhDf-GAd8TQ"
sermon_link3 = "https://www.youtube.com/watch?v=6-xx_mt2ung"
sermon_link4 = "https://www.youtube.com/watch?v=xrCeXb1EnkY"
sermon_link5 = "https://www.youtube.com/watch?v=AEa2QH0wYQc"