chapter_1_time = "0:25"
chapter_2_time = "2:58"
chapter_3_time = "5:00"
chapter_4_time = "7:35"
chapter_5_time = "10:02"
chapter_6_time = "12:07"

study_link1 = "https://www.youtube.com/watch?v=S-LRBZKGhe0"
study_link2 = "https://www.youtube.com/watch?v=5QTQHQroqas"
study_link3 = "https://www.youtube.com/shorts/t9pTqmLPCFU"
study_link4 = "https://www.youtube.com/watch?v=eIX-3lkKm6I"
study_link5 = "https://www.youtube.com/watch?v=6nN6C2sknj0"
study_link6 = "https://www.youtube.com/watch?v=bABEqu2iTMU"
study_link7 = "https://www.youtube.com/watch?v=U2XUh8shzrY"
study_link8 = "https://www.youtube.com/watch?v=bgeHTU5OHTo"
study_link9 = "https://www.youtube.com/watch?v=MaJVoG7qNIY"

sermon_link1 = "https://www.youtube.com/watch?v=nnPJbrVUrsc"
sermon_link2 = "https://www.youtube.com/watch?v=bWeSZs41fls"
sermon_link3 = "https://www.youtube.com/watch?v=Uni18vJWEoo"
sermon_link4 = "https://www.youtube.com/watch?v=b-nEc71xTW0"