chapter_1_time = "0:25"
chapter_2_time = "3:29"
chapter_3_time = "5:47"
chapter_4_time = "7:53"
chapter_5_time = "8:37"
chapter_6_time = "10:37"

study_link1 = "https://www.youtube.com/watch?v=VeKgfUGtcI0"
study_link2 = "https://www.youtube.com/watch?v=r5T6pkYp1xg"
study_link3 = "https://www.youtube.com/watch?v=CzwYWb4POJc"
study_link4 = "https://www.youtube.com/watch?v=9LdOgvVGxeQ"
study_link5 = "https://www.youtube.com/watch?v=Jh9cXa2rmHA"
study_link6 = "https://www.youtube.com/watch?v=I4-jKdYfyCQ"
study_link7 = "https://www.youtube.com/watch?v=lNGwsHKzCZI"
study_link8 = "https://www.youtube.com/watch?v=FmaYSxu1oVE"

sermon_link1 = "https://www.youtube.com/watch?v=H9rKLNTNT4w"
sermon_link2 = "https://www.youtube.com/watch?v=sNrcw0WT9ig"
sermon_link3 = "https://www.youtube.com/watch?v=nm7dy_4LVVA"
sermon_link4 = "https://www.youtube.com/watch?v=fGGKrmUZ-hg"