chapter_1_time = "0:25"
chapter_2_time = "2:57"
chapter_3_time = "7:48"
chapter_4_time = "9:53"
chapter_5_time = "11:58"

study_link1 = "https://www.youtube.com/watch?v=hErJeHuIaF0"
study_link2 = "https://www.youtube.com/watch?v=CFDbm_fGzrU"
study_link3 = "https://www.youtube.com/watch?v=0pSwB7y2z4o"
study_link4 = "https://www.youtube.com/watch?v=1UuYLsDO08Y"
study_link5 = "https://www.youtube.com/watch?v=11FTk05nWhE"
study_link6 = "https://www.youtube.com/watch?v=u-LvOF4BNGA"
study_link7 = "https://www.youtube.com/watch?v=oK5sum-LFFA"
study_link8 = "https://www.youtube.com/watch?v=kTibRihsOdg"

sermon_link1 = "https://www.youtube.com/watch?v=iBsGdtxVpPc"
sermon_link2 = "https://www.youtube.com/watch?v=JjSMLYQENI8"
sermon_link3 = "https://www.youtube.com/watch?v=2T44BhY2d74"
sermon_link4 = "https://www.youtube.com/watch?v=9wFp7ytj9g8"
sermon_link5 = "https://www.youtube.com/watch?v=pR7FE08HjW4"