chapter_1_time = "0:25"
chapter_2_time = "2:34"
chapter_3_time = "5:07"
chapter_4_time = "8:02"
chapter_5_time = "10:55"

study_link1 = "https://www.youtube.com/watch?v=2yVwKtFdJ_I"
study_link2 = "https://www.youtube.com/watch?v=p1n214d8XQo"
study_link3 = "https://www.youtube.com/watch?v=tTa3X_PWvm4"
study_link4 = "https://www.youtube.com/watch?v=EM9pDu5Tc24"
study_link5 = "https://www.youtube.com/watch?v=62YO-bPqq8Y"
study_link6 = "https://www.youtube.com/watch?v=28HVFJttJiQ"
study_link7 = "https://www.youtube.com/watch?v=aTToBMda3VE"
study_link8 = "https://www.youtube.com/watch?v=pjKdOB68P94"
study_link9 = "https://www.youtube.com/watch?v=NReCXxWOZXc"

sermon_link1 = "https://www.youtube.com/watch?v=UBlZCjRzB3E"
sermon_link2 = "https://www.youtube.com/watch?v=lC-u9izpCBU"
sermon_link3 = "https://www.youtube.com/watch?v=5qvW11fuGpg"
sermon_link4 = "https://www.youtube.com/watch?v=vnbiJ5S0hKk"