chapter_1_time = "0:25"
chapter_2_time = "2:21"
chapter_3_time = "4:59"
chapter_4_time = "7:21"
chapter_5_time = "9:35"

study_link1 = "https://www.youtube.com/watch?v=8LceNxnna4M"
study_link2 = "https://www.youtube.com/watch?v=vV64EyiawU4"
study_link3 = "https://www.youtube.com/watch?v=_wb6CvvSZ5Q"
study_link4 = "https://www.youtube.com/watch?v=L11aniUYocw"
study_link5 = "https://www.youtube.com/watch?v=SUWBelEa_6o"
study_link6 = "https://www.youtube.com/watch?v=coNf5_Tz7Fs"
study_link7 = "https://www.youtube.com/watch?v=Ji4Z_kJiCYA"
study_link8 = "https://www.youtube.com/watch?v=DX3tSWQNwDk"

sermon_link1 = "https://www.youtube.com/watch?v=pR7FE08HjW4"
sermon_link2 = "https://www.youtube.com/watch?v=Lo6b4dckj5A"
sermon_link3 = "https://www.youtube.com/watch?v=FQJ6MFyQjZs"
sermon_link4 = "https://www.youtube.com/watch?v=9vPmdmD9hRA"