chapter_1_time = "0:25"
chapter_2_time = "1:54"
chapter_3_time = "3:43"
chapter_4_time = "5:14"
chapter_5_time = "8:05"
chapter_6_time = "10:32"

study_link1 = "https://www.youtube.com/watch?v=q8wLTsmFAUk"
study_link2 = "https://www.youtube.com/watch?v=6FVvCcPUmhM"
study_link3 = "https://www.youtube.com/watch?v=1zTjZwkN2UY"
study_link4 = "https://www.youtube.com/watch?v=hfYsvcmzNM8"
study_link5 = "https://www.youtube.com/watch?v=YLZvJXmP7fo"
study_link6 = "https://www.youtube.com/watch?v=QF1LYafd5G8"
study_link7 = "https://www.youtube.com/watch?v=vR4g6_TkKD4"
study_link8 = "https://www.youtube.com/watch?v=YNFBQrzVRJk"

sermon_link1 = "https://www.youtube.com/watch?v=pwv6qot7MZ4"
sermon_link2 = "https://www.youtube.com/watch?v=abVAUELTmz8"
sermon_link3 = "https://www.youtube.com/watch?v=B7N04XIkSTQ"