chapter_1_time = "0:25"
chapter_2_time = "3:15"
chapter_3_time = "6:17"
chapter_4_time = "8:58"
chapter_5_time = "10:35"

study_link1 = "https://www.youtube.com/watch?v=2JXpzNPt67U"
study_link2 = "https://www.youtube.com/watch?v=OxiAikEk2vU"
study_link3 = "https://www.youtube.com/watch?v=4vAq9sWgZ74"
study_link4 = "https://www.youtube.com/watch?v=FHy34yGR57k"
study_link5 = "https://www.youtube.com/watch?v=7pfqvLmhZUk"
study_link6 = "https://www.youtube.com/watch?v=jOKDZKNnJWA"
study_link7 = "https://www.youtube.com/watch?v=e9BMU9aMRJw"
study_link8 = "https://www.youtube.com/watch?v=9HDuv3ghRfo"

sermon_link1 = "https://www.youtube.com/watch?v=g7OLQqYk708"
sermon_link2 = "https://www.youtube.com/watch?v=XZ99sbrQCuU"
sermon_link3 = "https://www.youtube.com/watch?v=bQjJfgdIllA"