chapter_1_time = "0:25"
chapter_2_time = "2:04"
chapter_3_time = "3:17"
chapter_4_time = "5:06"
chapter_5_time = "8:28"
chapter_6_time = "11:22"

study_link1 = "https://www.youtube.com/watch?v=kWSG5okmUr8"
study_link2 = "https://www.youtube.com/watch?v=Zg3jbCtIEcQ"
study_link3 = "https://www.youtube.com/watch?v=PZCErpzLO1E"
study_link4 = "https://www.youtube.com/watch?v=5q37CoOMVWs"
study_link5 = "https://www.youtube.com/watch?v=xk6oCuk7vWg"
study_link6 = "https://www.youtube.com/watch?v=gbks-45i4kY"
study_link7 = "https://www.youtube.com/watch?v=MvFfJTFCZSM"
study_link8 = "https://www.youtube.com/watch?v=pAVytaW3Zlc"
study_link9 = "https://www.youtube.com/watch?v=fOCu3hfHl08"

sermon_link1 = "https://www.youtube.com/watch?v=JhrOFbe0190"
sermon_link2 = "https://www.youtube.com/watch?v=ugJ4kR7kCvk"
sermon_link3 = "https://www.youtube.com/watch?v=ZGDcw8RUowg"
sermon_link4 = "https://www.youtube.com/watch?v=sGAPIlA9m-Q"
sermon_link5 = "https://www.youtube.com/watch?v=1ddPHTceuvU"