chapter_1_time = "0:25"
chapter_2_time = "2:31"
chapter_3_time = "4:21"
chapter_4_time = "6:53"
chapter_5_time = "9:31"
chapter_6_time = "11:47"

study_link1 = "https://www.youtube.com/watch?v=WoSOoqSRPvg"
study_link2 = "https://www.youtube.com/watch?v=mUjodEabN08"
study_link3 = "https://www.youtube.com/watch?v=J8rNitDXO1A"
study_link4 = "https://www.youtube.com/shorts/hiidvUMtDOQ"
study_link5 = "https://www.youtube.com/watch?v=NQmwg96Wr5g"
study_link6 = "https://www.youtube.com/watch?v=LhZ1wghaEcw"
study_link7 = "https://www.youtube.com/watch?v=jk9d7ybeviY"
study_link8 = "https://www.youtube.com/watch?v=eakw62uWGTo"
study_link9 = "https://www.youtube.com/watch?v=4ZmE6m-wiG8"

sermon_link1 = "https://www.youtube.com/watch?v=gIgFriRkJNs"
sermon_link2 = "https://www.youtube.com/watch?v=H_6fF4KneLo"
sermon_link3 = "https://www.youtube.com/watch?v=E8jY6wJ0gwQ"
sermon_link4 = "https://www.youtube.com/watch?v=XSQ3s2oF-ns"