chapter_1_time = "0:25"
chapter_2_time = "3:21"
chapter_3_time = "5:18"
chapter_4_time = "6:51"
chapter_5_time = "9:24"
chapter_6_time = "11:19"

study_link1 = "https://www.youtube.com/watch?v=xcdhklj0Z1Q"
study_link2 = "https://www.youtube.com/watch?v=ed4rVdaZ-EQ"
study_link3 = "https://www.youtube.com/watch?v=V93wgcHJ0lo"
study_link4 = "https://www.youtube.com/watch?v=kh5dgNzG89Y"
study_link5 = "https://www.youtube.com/watch?v=51HiUHHEihc"
study_link6 = "https://www.youtube.com/shorts/iBEJ4nEVOqY"
study_link7 = "https://www.youtube.com/watch?v=47RH5xwdr_A"
study_link8 = "https://www.youtube.com/watch?v=ua90td1JTaU"

sermon_link1 = "https://www.youtube.com/watch?v=ciJ3hNo23fQ"
sermon_link2 = "https://www.youtube.com/watch?v=2NiFxNB4Soo"
sermon_link3 = "https://www.youtube.com/watch?v=XMIyO7IrVT0"
sermon_link4 = "https://www.youtube.com/watch?v=JhrOFbe0190"