chapter_1_time = "0:25"
chapter_2_time = "1:49"
chapter_3_time = "4:16"
chapter_4_time = "5:43"
chapter_5_time = "7:35"
chapter_6_time = "10:04"

study_link1 = "https://www.youtube.com/watch?v=aTToBMda3VE"
study_link2 = "https://www.youtube.com/playlist?list=PLxaDcwyjYomyL3-dlgZ1qqjeo7vJaKBT7"
study_link3 = "https://www.youtube.com/watch?v=hklLnO47APs"
study_link4 = "https://www.youtube.com/watch?v=Ai4AHSsdNp0"
study_link5 = "https://www.youtube.com/watch?v=gs5VzPK8rw0"
study_link6 = "https://www.youtube.com/watch?v=GCXgMpy_WKc"
study_link7 = "https://www.youtube.com/watch?v=S-LRBZKGhe0"

sermon_link1 = "https://www.youtube.com/watch?v=wpTpc8H0XHw"
sermon_link2 = "https://www.youtube.com/watch?v=Sq98kwep_a4"
sermon_link3 = "https://www.youtube.com/watch?v=QxKRH-9IRCg"
sermon_link4 = "https://www.youtube.com/watch?v=Bmr2j-H0O4M"