chapter_1_time = "0:25"
chapter_2_time = "2:22"
chapter_3_time = "6:56"
chapter_4_time = "9:54"
chapter_5_time = "12:17"

study_link1 = "https://www.youtube.com/watch?v=gs5VzPK8rw0"
study_link2 = "https://www.youtube.com/watch?v=XiOili7CB80"
study_link3 = "https://www.youtube.com/watch?v=P2z7lIAHkvc"
study_link4 = "https://www.youtube.com/watch?v=C4kiExwVA9g"
study_link5 = "https://www.youtube.com/watch?v=V1DeAFw96Dg"
study_link6 = "https://www.youtube.com/watch?v=OTS1tMC38AQ"
study_link7 = "https://www.youtube.com/watch?v=B-60LEUZNFQ"
study_link8 = "https://www.youtube.com/watch?v=bhRROZWgMmc"
study_link9 = "https://www.youtube.com/watch?v=EOkIvuxKFm8"

sermon_link1 = "https://www.youtube.com/watch?v=EpJhgK1yT5M"
sermon_link2 = "https://www.youtube.com/watch?v=ZGGxVS7Wu9I"
sermon_link3 = "https://www.youtube.com/watch?v=MPm-TYv9gfk"
sermon_link4 = "https://www.youtube.com/watch?v=UCjgwh_ogrU"