chapter_1_time = "0:25"
chapter_2_time = "1:27"
chapter_3_time = "4:18"
chapter_4_time = "5:52"
chapter_5_time = "7:43"
chapter_6_time = "9:13"
chapter_7_time = "10:27"

study_link1 = "https://www.youtube.com/watch?v=Ph3N7tZ5LV4"
study_link2 = "https://www.youtube.com/watch?v=f_VlGNnyazc"
study_link3 = "https://www.youtube.com/watch?v=skLz-1yDN3I"
study_link4 = "https://www.youtube.com/watch?v=EsB3X-uWC7w"
study_link5 = "https://www.youtube.com/watch?v=EsB3X-uWC7w"
study_link6 = "https://www.youtube.com/watch?v=cWVyCfha4LU"
study_link7 = "https://www.youtube.com/watch?v=hfYsvcmzNM8"
study_link8 = "https://www.youtube.com/watch?v=9nlvj9nNVCA"
study_link9 = "https://www.youtube.com/watch?v=2_-kxwCDrOg"

sermon_link1 = "https://www.youtube.com/watch?v=gg08g7lxRoI"
sermon_link2 = "https://www.youtube.com/watch?v=5JxJ5sFHEuA"
sermon_link3 = "https://www.youtube.com/watch?v=jVTELfJHxjU"