chapter_1_time = "0:25"
chapter_2_time = "2:19"
chapter_3_time = "7:02"
chapter_4_time = "10:38"
chapter_5_time = "12:21"

study_link1 = "https://www.youtube.com/watch?v=fwdhe-G0LFo"
study_link2 = "https://www.youtube.com/watch?v=AkFI07vLJA0"
study_link3 = "https://www.youtube.com/watch?v=wX7Eb-llxbE"
study_link4 = "https://www.youtube.com/watch?v=rKT-a2DqDSc"
study_link5 = "https://www.youtube.com/watch?v=8gARYCVYrkY"
study_link6 = "https://www.youtube.com/watch?v=AOxrDKCH2BQ"
study_link7 = "https://www.youtube.com/watch?v=M2VJelWl_Fs"
study_link8 = "https://www.youtube.com/watch?v=mkIyFRLI6eU"
study_link9 = "https://www.youtube.com/watch?v=8Wtl4CYSkoA"

sermon_link1 = "https://www.youtube.com/watch?v=V-hiu2qsVsw"
sermon_link2 = "https://www.youtube.com/watch?v=PA2J6mfN7Xw"
sermon_link3 = "https://www.youtube.com/watch?v=fY0afczuxjY"