chapter_1_time = "0:25"
chapter_2_time = "2:07"
chapter_3_time = "3:21"
chapter_4_time = "5:35"
chapter_5_time = "7:51"
chapter_6_time = "12:14"

study_link1 = "https://faculty.som.yale.edu/jameschoi/whychrist/"
study_link2 = "https://www.youtube.com/watch?v=bbsfqB5ngvc"
study_link3 = "https://www.youtube.com/watch?v=-ErnJF_nwBk&list=PL1mr9ZTZb3TUYymBPce08oyuhnHLLkR_B"
study_link4 = "https://www.youtube.com/watch?v=wWhIVFJ4xUo"
study_link5 = "https://www.youtube.com/shorts/wk90Rh4TGeo"
study_link6 = "https://www.youtube.com/watch?v=wM0IKLv7KrE"
study_link7 = "https://www.youtube.com/watch?v=nJbHFw2Hksc"
study_link8 = "https://www.youtube.com/watch?v=ZaGrKLGaoZs"

sermon_link1 = "https://www.youtube.com/watch?v=2Ugjpi9z9FM"
sermon_link2 = "https://www.youtube.com/watch?v=QBUuFqj46nY"
sermon_link3 = "https://www.youtube.com/watch?v=izB1852Hw04"
sermon_link4 = "https://www.youtube.com/watch?v=7ilEyczPr4A"